# Generated by Django 5.2.9 on 2025-12-23 17:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ImageField(upload_to='badges/')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('priorty', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2025, 12, 23))),
                ('end_date', models.DateField(default=datetime.date(2025, 12, 24))),
            ],
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['username'], name='main_myuser_usernam_128df4_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['email'], name='main_myuser_email_9539c0_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['role'], name='main_myuser_role_528a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['is_active'], name='main_myuser_is_acti_afb670_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['username', 'email'], name='main_myuser_usernam_bb267b_idx'),
        ),
        migrations.AddField(
            model_name='plan',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.badge'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sub_plan',
            field=models.ManyToManyField(blank=True, related_name='sub_plans', to='main.plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plandate'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['priorty'], name='main_plan_priorty_4ccdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_complete'], name='main_plan_is_comp_5cda17_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['name'], name='main_plan_name_0eb3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['description'], name='main_plan_descrip_8c022f_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['date'], name='main_plan_date_id_71f7be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('name', 'description')},
        ),
    ]
