# Generated by Django 5.2.9 on 2025-12-23 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_badge_plan_plandate_alter_myuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-priority', 'start_date']},
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='main_plan_priorty_4ccdd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='main_plan_descrip_8c022f_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='main_plan_date_id_71f7be_idx',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='priorty',
            new_name='priority',
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plan',
            name='sub_plans',
            field=models.ManyToManyField(blank=True, related_name='parent_plans', to='main.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.badge'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['priority'], name='main_plan_priorit_f48cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['start_date'], name='main_plan_start_d_27b40c_idx'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='sub_plan',
        ),
        migrations.DeleteModel(
            name='PlanDate',
        ),
    ]
