# Generated by Django 5.2.9 on 2025-12-23 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_board_myuser_boards_plan_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.badge'),
        ),
    ]
