# Generated by Django 5.2.9 on 2025-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_board_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_check_complete',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_check_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
