# Generated by Django 5.2.9 on 2025-12-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_plan_last_check_complete_plan_last_check_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sub_plans',
        ),
        migrations.AddField(
            model_name='plan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_plans', to='main.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_check_complete',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
