# Generated by Django 5.2.9 on 2025-12-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_plan_sub_plans_plan_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='myuser',
            name='main_myuser_usernam_128df4_idx',
        ),
        migrations.RemoveIndex(
            model_name='myuser',
            name='main_myuser_email_9539c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='myuser',
            name='main_myuser_role_528a5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='myuser',
            name='main_myuser_is_acti_afb670_idx',
        ),
        migrations.RemoveIndex(
            model_name='myuser',
            name='main_myuser_usernam_bb267b_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='main_plan_name_0eb3a8_idx',
        ),
    ]
