# Generated by Django 5.2.9 on 2025-12-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('title', models.CharField(help_text='Напр: Основной или Праздничный', max_length=50, verbose_name='Название пресета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание пресета')),
                ('site_name', models.CharField(default='DailyDo', max_length=100)),
                ('nav_color', models.CharField(default='#ffffff', max_length=7)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
    ]
