# Generated by Django 5.2.9 on 2025-12-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='can_signup',
            field=models.BooleanField(default=True, help_text='Разрешить регистрацию'),
        ),
    ]
